branch-defaults:
  master:
    environment: GoShare--back-end-dev
    group_suffix: null
global:
  application_name: GoShare::back-end
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 1.12.6
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
